medsbuy/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('seller/', include('seller.urls')),
    path('', include('register.urls')),
    path('', include("django.contrib.auth.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path, include

from . import views

app_name = 'seller'
urlpatterns = [
    path('', views.IndexView, name='new'),
    path('dashboard', views.DashboardView, name='dash'),
    path('companydetails/', views.CompanyDetailView, name='company'),
    path('bankdetails/', views.BankDetailView, name='bank'),
    path('businessdetails/', views.BusinessDetailView, name='business'),
    path('products/', views.ProductsView, name='products'),
    path('products/add/', views.AddProductView, name='add_product'),
    path('products/update/<int:pk>',
         views.UpdateProductView, name='update_product'),
    path('products/delete/<int:pk>',
         views.DeleteProductView, name='delete_product'),
]

seller/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE


class CompanyDetails(models.Model):
    seller = models.OneToOneField(
        User, on_delete=CASCADE, related_name='CompanyDetails',)

    company_name = models.CharField(max_length=150,)
    company_name = models.CharField(max_length=150,)
    GSTIN = models.CharField(max_length=15,)
    address_l1 = models.CharField(
        max_length=300, verbose_name='Address Line 1')
    address_l2 = models.CharField(
        max_length=300, verbose_name='Address Line 2', blank=True, null=True,)
    pincode = models.IntegerField()
    city = models.CharField(max_length=150,)
    state = models.CharField(max_length=150,)
    country = models.CharField(max_length=150,)
    email = models.EmailField()
    contact_number = models.PositiveIntegerField()


class BankDetails(models.Model):
    seller = models.OneToOneField(
        User, on_delete=CASCADE,  related_name='BankDetails',)

    bank_name = models.CharField(max_length=150,)
    city = models.CharField(max_length=150,)
    state = models.CharField(max_length=150,)
    branch = models.CharField(max_length=150,)

    account_holder_name = models.CharField(max_length=150,)
    account_number = models.IntegerField()
    IFSC = models.CharField(max_length=100,)

    def __str__(self):
        return self.seller.username


class BusinessDetails(models.Model):
    seller = models.OneToOneField(
        User, on_delete=CASCADE,  related_name='BusinessDetails',)

    business_name = models.CharField(max_length=150,)

    GSTIN = models.CharField(max_length=15,)
    TAN = models.ImageField(upload_to='seller_details/TAN',)
    signature = models.ImageField(upload_to='seller_details/signature',)

    address_l1 = models.CharField(
        max_length=300, verbose_name='Address Line 1')
    address_l2 = models.CharField(
        max_length=300, verbose_name='Address Line 2', blank=True, null=True,)
    pincode = models.IntegerField()
    city = models.CharField(max_length=150,)
    state = models.CharField(max_length=150,)
    country = models.CharField(max_length=150,)

    business_type = models.CharField(max_length=150,)

    PersonalPAN = models.CharField(max_length=150,)
    BusinessPAN = models.CharField(max_length=150,)

    address_proof = models.ImageField(
        upload_to='seller_details/address_proof',)


class Products(models.Model):
    seller = models.ForeignKey(
        User, related_name='products', on_delete=CASCADE)
    # order = models.ForeignKey(
    #     Orders, related_name='products', on_delete=CASCADE)

    product_name = models.CharField(max_length=300,)
    product_image = models.ImageField(
        upload_to='product_images/', blank=True, null=True,)

    product_price = models.FloatField()
    product_MRP = models.FloatField()

    product_quantity = models.IntegerField()

    STATUS = (
        ('Active', 'Active'),
        ('Disabled', 'Disabled'),
        ('Hidden', 'Hidden'),
        ('Stock Out', 'Stock Out'),
    )

    product_status = models.CharField(
        max_length=100, choices=STATUS, default='Active',)

    def __str__(self):
        return self.product_name

    def stocked_out(self):
        if self.product_quantity == 0:
            return True
        else:
            return False

    def is_hidden(self):
        if self.product_status == 'Hidden':
            return True
        else:
            return False

    def disabled(self):
        if self.product_status == 'Disabled':
            return True
        else:
            return False


class Orders(models.Model):
    seller = models.ForeignKey(User, on_delete=CASCADE)
    order_name = models.CharField(max_length=100, blank=True, null=True)
    products = models.ManyToManyField(Products,)
    STATUS = [
        ('Hub', 'Hub'),
        ('Active', 'Active'),
        ('Returned', 'Returned'),
        ('Cancelled', 'Cancelled'),
    ]
    order_status = models.CharField(max_length=100, choices=STATUS,)

    def __str__(self):
        return self.order_name


class AdditionalDetail(models.Model):
    product = models.ForeignKey(Orders, on_delete=CASCADE)
    name = models.CharField(max_length=100,)
    description = models.CharField(max_length=300,)

seller/forms.py
from django import forms
from .models import *
from django.forms import ModelForm


class CompanyDetailsForm(ModelForm):
    class Meta:
        model = CompanyDetails
        exclude = ["seller"]
        widgets = {'pincode': forms.TextInput(),
                   'contact_number': forms.TextInput(),
                   }


class BankDetailsForm(ModelForm):
    class Meta:
        model = BankDetails
        exclude = ["seller"]
        widgets = {'account_number': forms.TextInput()}
        # 'bank_name': forms.TextInput(
        #     attrs={'placeholder': 'Bank Name'}),


class BusinessDetailsForm(ModelForm):
    class Meta:
        model = BusinessDetails
        exclude = ["seller"]
        widgets = {'pincode': forms.TextInput()}


class AddProductForm(ModelForm):
    class Meta:
        model = Products
        exclude = ["seller", ]

seller/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .forms import *
# from .models import *


@login_required(login_url='login')
def IndexView(request):
    template_name = 'seller/new_user.html'

    seller = request.user
    context = {'seller': seller,
               }

    return render(request, template_name, context)


@login_required(login_url='login')
def DashboardView(request):
    template_name = 'seller/index.html'

    seller = request.user
    products = seller.products.all()
    # products = Products.objects.all()
    product_count = products.count()

    stock_below_5_products = []
    for product in products:
        if product.product_quantity <= 5:
            stock_below_5_products.append(product)

    stock_below_5_prod_count = len(stock_below_5_products)

    stocked_out_products = []
    for product in products:
        if product.stocked_out():
            stocked_out_products.append(product)

    stocked_out_prod_count = len(stocked_out_products)

    hidden_disabled_products = []
    for product in products:
        if product.is_hidden() or product.disabled():
            hidden_disabled_products.append(product)

    hidden_disabled_prod_count = len(hidden_disabled_products)

    context = {'product_count': product_count,
               'stocked_out_prod_count': stocked_out_prod_count,
               'stock_below_5_prod_count': stock_below_5_prod_count,
               'stock_below_5_products': stock_below_5_products,
               'hidden_disabled_prod_count': hidden_disabled_prod_count,
               'seller': seller,
               }

    return render(request, template_name, context)


def CompanyDetailView(request):
    template_name = 'seller/form.html'
    previous_url = request.META.get('HTTP_REFERER')

    form_title = 'Sell on Medsbuy'
    form_heading = 'Company Details'
    form_button_text = 'Submit'

    user = request.user

    if hasattr(user, 'CompanyDetails'):
        form = CompanyDetailsForm(instance=user.CompanyDetails)
    else:
        form = CompanyDetailsForm()

    if request.method == 'POST':
        if hasattr(user, 'CompanyDetails'):
            form = CompanyDetailsForm(instance=user.CompanyDetails)
        else:
            form = CompanyDetailsForm()

        if form.is_valid():
            details = form.save(commit=False)
            details.seller = user
            details.save()

            return redirect('/seller/')

    context = {'form': form,
               'form_title': form_title,
               'form_heading': form_heading,
               'form_button_text': form_button_text,
               'previous_url': previous_url,
               }

    return render(request, template_name, context)


def BankDetailView(request):
    template_name = 'seller/form.html'
    previous_url = request.META.get('HTTP_REFERER')

    form_title = 'Sell on Medsbuy'
    form_heading = 'Bank Details'
    form_button_text = 'Submit'

    user = request.user

    if hasattr(user, 'BankDetails'):
        form = BankDetailsForm(instance=user.BankDetails)
    else:
        form = BankDetailsForm()

    if request.method == 'POST':
        if hasattr(user, 'BankDetails'):
            form = BankDetailsForm(instance=user.BankDetails)
        else:
            form = BankDetailsForm()

        if form.is_valid():
            details = form.save(commit=False)
            details.seller = user
            details.save()

            return redirect('/seller/')

    context = {'form': form,
               'form_title': form_title,
               'form_heading': form_heading,
               'form_button_text': form_button_text,
               'previous_url': previous_url,
               }

    return render(request, template_name, context)


def BusinessDetailView(request):
    template_name = 'seller/form.html'
    previous_url = request.META.get('HTTP_REFERER')

    form_title = 'Sell on Medsbuy'
    form_heading = 'Business Details'
    form_button_text = 'Submit'

    user = request.user

    if hasattr(user, 'BusinessDetails'):
        form = BusinessDetailsForm(instance=user.BusinessDetails)
    else:
        form = BusinessDetailsForm()

    if request.method == 'POST':
        if hasattr(user, 'BusinessDetails'):
            form = BusinessDetailsForm(instance=user.BusinessDetails)
        else:
            form = BusinessDetailsForm()

        if form.is_valid():
            details = form.save(commit=False)
            details.seller = user
            details.save()

            return redirect('/seller/')

    context = {'form': form,
               'form_title': form_title,
               'form_heading': form_heading,
               'form_button_text': form_button_text,
               'previous_url': previous_url,
               }

    return render(request, template_name, context)


@login_required(login_url='login')
def ProductsView(request):
    template_name = 'seller/listing.html'
    seller = request.user
    products = seller.products.all()
    # products = Products.objects.all()

    context = {'products': products,
               }

    return render(request, template_name, context)


def AddProductView(request):
    template_name = 'seller/form.html'
    previous_url = request.META.get('HTTP_REFERER')

    form_title = 'Sell on Medsbuy'
    form_heading = 'Add New Product'
    form_button_text = 'Add Product'

    form = AddProductForm()

    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)
        form.instance.seller = request.user
        if form.is_valid():

            form.save()

            return redirect('/seller/products')

    context = {'form': form,
               'form_title': form_title,
               'form_heading': form_heading,
               'form_button_text': form_button_text,
               'previous_url': previous_url,
               }

    return render(request, template_name, context)


def UpdateProductView(request, pk):
    template_name = 'seller/form.html'
    previous_url = request.META.get('HTTP_REFERER')

    form_title = 'Sell on Medsbuy'
    form_heading = 'Edit Product'
    form_button_text = 'Update'

    product = request.user.products.get(pk=pk)

    form = AddProductForm(instance=product)

    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES,
                              instance=product)
        # form.instance.seller = request.user
        if form.is_valid():

            form.save()

            return redirect('/seller/products')

    context = {'form': form,
               'form_title': form_title,
               'form_heading': form_heading,
               'form_button_text': form_button_text,
               'previous_url': previous_url,
               }

    return render(request, template_name, context)


def DeleteProductView(request, pk):
    template_name = 'seller/form.html'
    previous_url = request.META.get('HTTP_REFERER')

    form_title = 'Sell on Medsbuy'
    form_heading = 'Delete Product'
    form_button_text = 'Confirm Delete'

    product = request.user.products.get(pk=pk)

    heading_text = "Are you sure to delete product '" + product.product_name + "' ?"

    if request.method == 'POST':
        product.delete()

        return redirect('/seller/products')

    context = {'form_title': form_title,
               'form_heading': form_heading,
               'form_button_text': form_button_text,
               'heading_text': heading_text,
               'previous_url': previous_url,
               }

    return render(request, template_name, context)

seller/templates/seller/add_product.html
{% extends 'seller/form.html' %}
<!-- --  -->
{% block heading %} Add New Product {% endblock %}
<!-- --  -->
{% block button %} Add Product {% endblock %}

seller/templates/seller/bank_detail.html
{% extends 'seller/form.html' %}
<!-- --  -->
{% block heading %} Bank Details {% endblock %}
<!-- --  -->

seller/templates/seller/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sell on Medsbuy</title>


    <!-- Compiled and minified Materialize CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

    <link rel="stylesheet" href="{% static 'seller/css/style.css' %}">
    <!-- --  -->
    {% block addons %}{% endblock %}

</head>

<body>
    <nav>
        <div class="nav-wrapper blue">

            <a href="{% url 'seller:dash' %}" class="brand-logo hide-on-large-only">
                Medsbuy Seller
            </a>
            <ul id="nav-mobile" class="hide-on-med-and-down">
                <li>
                    <a class="app-logo" href="{% url 'seller:dash' %}">
                        Medsbuy
                    </a>
                </li>
                <li><a href="{% url 'seller:dash' %}">Dashboard</a></li>
                <!-- Dropdown Trigger -->
                <li>
                    <ul id="dropdown" class="dropdown-content">
                        <li><a href="#">Hub Order</a></li>
                        <li><a href="#">Active Order</a></li>
                        <li><a href="#">Cancelled Order</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Return Order</a></li>
                        <li><a href="#">Track Order</a></li>
                    </ul>
                    <a class="dropdown-button" href="#" data-activates="dropdown">Orders<i class = "mdi-navigation-arrow-drop-down right" style="line-height: inherit; height: inherit;"></i></a>
                </li>
                <li>
                    <ul id="dropdown2" class="dropdown-content">
                        <li><a href="{%url 'seller:add_product'  %}">Add Product</a></li>
                        <li><a href="{%url 'seller:products'  %}">Manage Products</a></li>
                        <li><a href="#">Track Approval</a></li>
                    </ul>
                    <a class="dropdown-button" href="#" data-activates="dropdown2">Listing<i class = "mdi-navigation-arrow-drop-down right" style="line-height: inherit; height: inherit;"></i></a>
                </li>
                <li><a href="# ">Rate &amp; Review</a></li>
                <li><a href="# ">Payment</a></li>
                <li><a href="# ">Performance</a></li>
                <li><a href="# ">Opportunities</a></li>
                <li>
                    <a href="# ">
                        <i class="material-icons ">notifications</i>
                    </a>
                </li>
            </ul>
            <ul id="nav-mobile " class="right hide-on-med-and-down ">
                <li>
                    <i class="material-icons ">account_circle</i>
                </li>
                <li>
                    <a href="# ">
                        {{ seller.username }}
                    </a>
                </li>
                <li>
                    <a href="# ">
                        <i class="material-icons ">more_vert</i>
                    </a>
                </li>


            </ul>

        </div>
    </nav>
    {% block main %} {% endblock %}
</body>




</html>

seller/templates/seller/base_0.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>sell with medsbuy</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</head>

<body>

    <!-- --  -->
    {% block main %}{% endblock %}

</body>

</html>

seller/templates/seller/business_detail.html
{% extends 'seller/form.html' %}
<!-- --  -->
{% block heading %} Business Details {% endblock %}
<!-- --  -->

seller/templates/seller/form.html
{% load static %} {% load crispy_forms_tags %}
<!DOCTYPE HTML>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="">
    <meta name="keywords" content="">

    <title>{% block title %}{{form_title}}{% endblock %}</title>

    <link href="images/favicon.ico" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="{% static 'seller/assets/js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="{% static 'seller/assets/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'seller/assets/css/bootstrap.css' %}" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="{% static 'seller/assets/fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

    <!-- custom style -->

    <link href="{% static 'seller/assets/css/ui.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'seller/assets/css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'seller/assets/css/responsive.css' %}" rel="stylesheet" type="text/css" />

    <!-- custom javascript -->
    <script src="{% static 'seller/assets/js/script.js' %}" type="text/javascript"></script>

</head>

<body>




    <!-- ========================= SECTION MAIN  ========================= -->
    <section class="section-main" style="padding-bottom: 10px;">

        <form class="jotform-form" action="#" method="POST" enctype="multipart/form-data" id="202734202737450"
            autocomplete="on">
            <!-- --  -->
            {% csrf_token %}
            <div role="main" class="form-all">
                <div class="form-header-group  header-default">

                    <div class="header-text httac htvam">
                        <h2>{% block heading %}{{form_heading}}{% endblock %}</h2>

                    </div>
                </div>
                <div class="mx-5">
                    <div class="mx-5">
                        {% if heading_text %}
                        <h5 class="mt-5 text-center">{{heading_text}}</h5>
                        {% endif %}
                        <br> {{form|crispy}}
                    </div>
                </div>
                <div class="form-buttons-wrapper">
                    <input type="submit" class="btn-secondary mb-3 mx-5"
                        value="{% block button %}{{form_button_text}}{% endblock%}">
                    <button onclick="window.location.href='{{previous_url}}'" type="button"
                        class="btn-primary">Cancel</button>
                </div>
            </div>
        </form>
    </section>
    <!-- ========================= SECTION MAIN END// ========================= -->

    <!-- ========================= FOOTER ========================= -->


    <!-- ========================= FOOTER END // ========================= -->



</body>

</html>

seller/templates/seller/listing.html
{% extends 'seller/base.html' %}
<!-- --  -->
{% block main %}

<div class="container">

    <h5>Product Listing <span><a href="{% url 'seller:add_product' %}" class="right">Add Product</a></span> </h5>


    <table class="responsive striped">
        <thead>
            <tr>
                <th></th>
                <th>Product Name/Code</th>
                <th>List Price</th>
                <th>MRP</th>
                <th>Quantity</th>
                <th>Status</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            {% for product in products %}
            <tr>
                <td>
                {% if product.product_image is not None  %}
                    <img src="{{ product.product_image.url }}" alt="Product Image" data-holder-rendered="true"
                        width="60" height="60">
                {% endif %}
                </td>
                <td>{{ product.product_name }}</td>
                <td>{{ product.product_price }}</td>
                <td>{{ product.product_MRP }}</td>
                <td>{{ product.product_quantity }}</td>
                <td>{{ product.product_status }}</td>
                <td>
                    <div>
                        <ul id="dropdown3" class="dropdown-content">
                            <li><a href="{% url 'seller:update_product' product.id %}">Edit</a></li>
                            <li><a href="{% url 'seller:delete_product' product.id %}">Delete</a></li>
                        </ul>
                        <a class="dropdown-button" href="#" data-activates="dropdown3"><i
                                class="material-icons">settings</i><i class="mdi-navigation-arrow-drop-down"
                                style="line-height: inherit; height: inherit;"></i></a>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
<!-- --  -->
{% endblock %}

seller/templates/seller/new_user.html
{% extends 'seller/base.html' %}
<!-- --  -->
{% block main %}
<div class="container">
    <h3 class=" center ">Welcome to <span class="green-text text-lighten-1 ">Medsbuy</span></h3>
    <div class="row ">
        <div class="col s0 m1 l2 "></div>
        <div class="col s12 m10 l8 ">
            <div class="row ">
                <h5 class="col s12 ">You are almost ready to start selling!</h5>
                <h6 class="col s12 grey-text ">Please complete all the steps below</h6>
                <!-- <div class="col s12 divider "></div> -->

                <div class="col s12 card-panel new-card top-card white ">
                    <div class="row ">
                        <div class="col s1 ">
                            <i class="material-icons new-icon blue-text text-lighten-1 ">article</i>
                        </div>
                        <div class="col s9 ">
                            <p>Company Details

                                <span>Display information, Pickup address, Primary & Login Detail</span>
                            </p>
                        </div>
                        <div class="col s2 ">
                            <a href="{% url 'seller:company' %}"
                                class="waves-effect waves-light blue new-btn btn ">View</a>
                        </div>
                    </div>
                </div>
                <div class="col s12 card-panel new-card top-card white ">
                    <div class="row ">
                        <div class="col s1 ">
                            <i class="material-icons new-icon teal-text text-lighten-1 ">account_balance</i>
                        </div>
                        <div class="col s9 ">
                            <p>Bank Details
                            </p>
                        </div>
                        <div class="col s2 ">
                            <a href="{% url 'seller:bank' %} "
                                class="waves-effect waves-light blue new-btn btn ">View</a>
                        </div>
                    </div>
                </div>
                <div class="col s12 card-panel new-card top-card white ">
                    <div class="row ">
                        <div class="col s1 ">
                            <i class="material-icons new-icon yellow-text text-darken-1 ">store</i>
                        </div>
                        <div class="col s9 ">
                            <p>Business Details

                                <span>KYC & Legal Detail </span>
                            </p>
                        </div>
                        <div class="col s2 ">
                            <a href="{% url 'seller:business' %} "
                                class="waves-effect waves-light blue new-btn btn ">View</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- --  -->
{% endblock %}